name: 機能追加
description: 新機能の実装や既存機能の改善を行うための Issue テンプレート
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能追加リクエスト
        新機能の実装や既存機能の改善について記載してください。

  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 実現したいこと、背景、目的などを簡潔に記載してください
    validations:
      required: true

  - type: textarea
    id: related-pbi
    attributes:
      label: 関連 PBI
      description: 関連する他の PBI（親課題以外）のリンクを記載してください

  - type: textarea
    id: tasks
    attributes:
      label: やること
      description: 作業の一覧をチェックリスト形式で記載してください
    validations:
      required: true

  - type: textarea
    id: out-of-scope
    attributes:
      label: やらないこと
      description: 対応範囲に含まれないこと、スコープ外の内容を記載してください

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 完了条件
      description: 完了とみなせる条件をチェックリスト形式で記載してください
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: 対応内容/Wiki
      description: 実装方針や設計内容を記載してください。詳細が Wiki にある場合はリンクを記載してください

  - type: textarea
    id: related-pr
    attributes:
      label: 関連 PR
      description: 対応する Pull Request の URL を記載してください

  - type: textarea
    id: notes
    attributes:
      label: メモ/補足
      description: 議論の経緯、注意点、その他共有しておきたいことを自由に記載してください
